config/routes.rb
Rails.application.routes.draw do
  devise_for :members

  get "/members/about" => "members#about"
  get "/members/top" => "members#top"
  get "/members/withdraw" => "members#withdraw"
  patch "/members/hide" => "members#hide"
  resources :members

  devise_scope :admin do
    root "admins/sessions#new"
  end

  devise_for :admins, controllers: {
    sessions: 'admins/sessions'
  }

  get 'admin/top' => "admin/homes#top"

  namespace :admin do
    resources :orders, only: [:index, :show, :update]
    # patch '/orders/:id/update' => 'orders#update'
    resources :order_details, only: [:update]
    resources :members, only: [:show, :edit, :update, :index]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :products, xcept: [:destroy]
    get '/search' => 'search#search'
  end

  namespace :member do
      resources :products, only: [:index, :show]
      resources :carts, only: [:index, :create, :update, :destroy]
      delete '/empty_item' => 'carts#empty_item'
      resources :cart_products
      resources :shipping_addresses, only: [:index, :create, :edit, :update, :destroy]
      post 'order/confirm' => "orders#confirm"
      get 'orders/thank' => "orders#thank"
      resources :orders, only: [:index, :show, :new, :create]
  end


end

app/models/order.rb
class Order < ApplicationRecord

	enum payment_method:{"クレジットカード": 0, "銀行振込": 1}

	belongs_to :member
	has_many :order_detail
	accepts_nested_attributes_for :order_detail

  attachment :image

  enum status: {入金待ち: 1, 入金確認: 2, 製作中: 3, 発送準備中: 4, 発送済み: 5}

  def payment_amount
  	self.postage + self.member.cart.total_price.floor
  end


  def full_address
  self.post_code + self.address + self.address_name
  end

  def full_name
    self.last_name + self.first_name
  end

  def price_include_tax(price)
    price = price*1.1
  "#{price.floor}円"
end

  def taxed_price(price)
      price * 1.1
    end


end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
before_action :authenticate_admin!

  def index
  	path = Rails.application.routes.recognize_path(request.referer)
  	path_controller = path[:controller]
  	path_action = path[:action]
  # topページから遷移　＝＞　当日注文の注文履歴
  	if path_controller == "admin/homes" && path_action == "top"
  	  @orders = Order.where(created_at: Time.now.all_day).page(params[:page]).reverse_order

  	  # 会員詳細からの遷移　＝＞　該当顧客の注文履歴
	  elsif path_controller == "admin/members" && path_action == "show"
	  @orders = Order.where(member_id: path[:id]).page(params[:page]).reverse_order

	  # ヘッダーからの遷移　＝＞　全顧客の注文履歴
	  else @orders = Order.all.page(params[:page]).reverse_order
	  end
  end

  def show
  	@order = Order.find(params[:id])
  	@order_details = @order.order_detail
  end

  def update
  	@order = Order.find(params[:id])
  	@order.update(order_params)
    @order_details = @order.order_detail
  	if @order.status == "入金確認"
  		@order_details.each do |order_detail|
  			order_detail.update(production_status: "製作待ち")
  		end
  	end
  	redirect_to request.referer
  end

  # def update_products
  # 	@product = OrderDetail.find(params[:id])
  # 	@product.update(order_detail_params)
  # end

  private

  def order_params
  	params.require(:order).permit(:status)
  end

  def order_detail_params
  	params.require(:order_detail).permit(:production_status)
  end

end

app/controllers/member/orders_controller.rb
class Member::OrdersController < ApplicationController
  before_action :set_member
  def new
    @order = Order.new
    @shipping_addresses = ShippingAddress.where(member_id: current_member.id)
  end

  def create
    @order = Order.new(order_params)
    @order.member_id = current_member.id
    @order.payment_method = params[:order][:payment_method]
    @order.address_option = params[:order][:address_option]
    @order.postal_code = params[:order][:postal_code]
    @order.address = params[:order][:address]
    @order.address_name = params[:order][:address_name]
    @order.total_amount = params[:order][:total_amount]
    @order.save
    @cart_products = CartProduct.where(cart_id: current_member.cart.id)
    @cart_products.each do |cp|
      @order_detail = @order.order_detail.new
      @order_detail.product_id = cp.product.id
      @order_detail.number = cp.number
      @order_detail.taxed_price = cp.tax_price
      @order_detail.save
      cp.destroy
    end

    if ShippingAddress.find_by(member_id: current_member.id, address: @order.address).nil?
      @shipping_address = ShippingAddress.new
      @shipping_address.post_code = @order.postal_code
      @shipping_address.address = @order.address
      @shipping_address.address_name = @order.address_name
      @shipping_address.member_id = current_member.id
      @shipping_address.save
    end
    redirect_to member_orders_thank_path
  end

  def confirm
    @order = Order.new
    @cart = current_member.cart
    @cart_products = CartProduct.where(cart_id: current_member.cart.id)
    @order.member_id = current_member.id
    @order.payment_method = params[:order][:payment_method]
    @order.address_option = params[:order][:address_option]
    if @order.address_option == 0
      @order.postal_code = current_member.post_code
      @order.address = current_member.address
      @order.address_name = current_member.last_name + current_member.first_name
    elsif @order.address_option == 1
      @select_address = params[:order][:select_address]
      @shipping_address = ShippingAddress.find(@select_address)
      @order.postal_code = @shipping_address.post_code
      @order.address = @shipping_address.address
      @order.address_name = @shipping_address.address_name
    elsif @order.address_option == 2
      @order.postal_code = params[:order][:postal_code]
      @order.address = params[:order][:address]
      @order.address_name = params[:order][:address_name]
    end
    # render :new and return if params[:back] || !@order.save
  end



  def thank
    current_member.cart.cart_products.destroy_all
  end


  def index
		@orders = Order.where(member_id: current_member.id).page(params[:page]).per(8)
    @order_detail = OrderDetail.find_by(order_id: @order)
    #@orders = @member.orders
	end

	def show
    @order = Order.find_by(id: params[:id])
    @order_details = @order.order_detail
  end


  private
  def set_member
    @member = current_member
  end
  def order_params
    params.permit(
      :postage,
      :payment_method,
      :total_amount,
      :postal_code,
      :address,
      :address_name,
      :address_option,
      order_detail_attributes: [:id,
                                :product_id,
                                :product_name,
                                :order_id,
                                :number,
                                :taxed_price,
                                :production_status]
    ).merge(member_id: current_member.id)

  end

  def shipping_address_params
    params.require(:shipping_address).permit(:member_id, :post_code, :address, :address_name)
  end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/member/order_helper.rb
module Member::OrderHelper
end

app/helpers/member/orders_helper.rb
module Member::OrdersHelper
end

app/views/admin/orders/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-10 col-xs-offset-2">
<h2>注文履歴一覧</h2>
<table class="table">
	<thead class="thead-light">
		<tr>
			<th>購入日時</th>
			<th>購入者</th>
			<th>注文個数</th>
			<th>注文ステータス</th>
			<th colspan="3"></th>
		</tr>
	</thead>
    	<% @orders.each do |order| %>
    	<tr>
    		<td><%= link_to order.created_at.strftime('%Y/%m/%d %H:%M:%S'), admin_order_path(order) %></td>
    		<td><%= order.member.last_name %> <%= order.member.first_name %></td>
    		<td><%= order.order_detail.sum(:number) %></td>
    		<td><%= order.status %></td>
    	</tr>
    	<% end %>
</table>
</div>
</div>
</div>
<%= paginate @orders %>

app/views/admin/orders/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-10 offset-2">
<h2>注文履歴詳細</h2>
<table class="table-info">
	<tr>
		<th>購入者</th>
		<td><%= @order.member.last_name%> <%=@order.member.first_name %></td>
	</tr>
	<tr>
		<th>配送先</th>
		<td><%= @order.address %></td>
		<td><%= @order.address_name %></td>
	</tr>
	<tr>
		<th>支払い方法</th>
		<td><%= @order.payment_method %></td>
	</tr>
	<tr>
		<th>注文ステータス</th>
		<td><%= form_for @order, url: {controller: 'admin/orders', action: 'update'} do |f| %>
			<%= f.select :status, Order.statuses.keys.to_a %>
			<%= f.submit "更新", class: "btn btn-primary btn-sm" %>
			<% end %>
		</td>
	</tr>
</table>
<table class="table table-borderless">
	<thead>
		<tr>
			<th>商品名</th>
			<th>単価（税込）</th>
			<th>数量</th>
			<th>小計</th>
			<th>制作ステータス</th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		<% sum_all = 0 %>
		<% @order_details.each do |order_detail| %>
		<tr>
			<td><%= order_detail.product.name %></td>
			<td><%= order_detail.taxed_price %></td>
			<td><%= order_detail.number %></td>
			<td><%= sum_total = order_detail.taxed_price.to_i * order_detail.number %>
				<% sum_all += sum_total %>
			</td>
			<%= form_for(order_detail, url:admin_order_detail_path(order_detail), method: :patch) do |f| %>
			<td><%= f.select :production_status, OrderDetail.production_statuses.keys.to_a %></td>
			<td><%= f.submit "更新", class: "btn btn-primary btn-sm" %></td>
			<% end %>
		</tr>
		<% end %>
	</tbody>
</table>
<table class="pull-right">
	<tr>
		<th>商品合計</th>
		<td><%= sum_all %>円</td>
	</tr>
	<tr>
		<th>送料</th>
		<td><%= @order.postage %>円</td>
	</tr>
	<tr>
		<th>請求金額合計</th>
		<td><%= @order.total_amount %>円</td>
	</tr>
</table>
</div>
</div>
</div>