config/routes.rb
Rails.application.routes.draw do
  devise_for :members

  get "/members/about" => "members#about"
  get "/members/top" => "members#top"
  get "/members/withdraw" => "members#withdraw"
  patch "/members/hide" => "members#hide"
  resources :members

  devise_scope :admin do
    root "admins/sessions#new"
  end

  devise_for :admins, controllers: {
    sessions: 'admins/sessions'
  }

  get 'admin/top' => "admin/homes#top"

  namespace :admin do
    resources :orders, only: [:index, :show, :update]
    # patch '/orders/:id/update' => 'orders#update'
    resources :order_details, only: [:update]
    resources :members, only: [:show, :edit, :update, :index]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :products, xcept: [:destroy]
    get '/search' => 'search#search'
  end

  namespace :member do
      resources :products, only: [:index, :show]
      resources :carts, only: [:index, :create, :update, :destroy]
      delete '/empty_item' => 'carts#empty_item'
      resources :cart_products
      resources :shipping_addresses, only: [:index, :create, :edit, :update, :destroy]
      post 'order/confirm' => "orders#confirm"
      get 'orders/thank' => "orders#thank"
      resources :orders, only: [:index, :show, :new, :create]
  end


end

app/models/member.rb
class Member < ApplicationRecord

	enum status: { 有効:false, 退会済み:true }

	has_many :orders
  has_many :shipping_addresses, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


 def full_address
		self.post_code + self.address + self.last_name + self.first_name
	end

  has_one :cart, dependent: :destroy

  def prepare_cart
  	current_member.cart || current_member.create_cart
  end

  def active_for_authentication?
    super && (self.status? == 有効?)
  end

  def inactive_message
   "退会済みです"
 end

end

app/models/order.rb
class Order < ApplicationRecord

	enum payment_method:{"クレジットカード": 0, "銀行振込": 1}

	belongs_to :member
	has_many :order_detail
	accepts_nested_attributes_for :order_detail

  attachment :image

  enum status: {入金待ち: 1, 入金確認: 2, 製作中: 3, 発送準備中: 4, 発送済み: 5}

  def payment_amount
  	self.postage + self.member.cart.total_price.floor
  end


  def full_address
  self.post_code + self.address + self.address_name
  end

  def full_name
    self.last_name + self.first_name
  end

  def price_include_tax(price)
    price = price*1.1
  "#{price.floor}円"
end

  def taxed_price(price)
      price * 1.1
    end


end

app/controllers/admin/members_controller.rb
class Admin::MembersController < ApplicationController
	before_action :authenticate_admin!

	def index
		@members = Member.page(params[:page]).per(8)
	end

	def show
		@member = Member.find(params[:id])
	end

	def edit
		@member = Member.find(params[:id])
	end


	def update
		@member = Member.find(params[:id])
		@member.update(member_params)
		if @member.update(member_params)
			redirect_to admin_member_path(@member.id)
	   else
			render :edit
	　　end
    end
end
    private
    def member_params
	    params.require(:member).permit(:first_name,:last_name,:first_name_kana,:last_name_kana,:email,:postal_code,:address,:phone_number,:encrypted_password,:status,:created_at,:updated_at)

    end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
before_action :authenticate_admin!

  def index
  	path = Rails.application.routes.recognize_path(request.referer)
  	path_controller = path[:controller]
  	path_action = path[:action]
  # topページから遷移　＝＞　当日注文の注文履歴
  	if path_controller == "admin/homes" && path_action == "top"
  	  @orders = Order.where(created_at: Time.now.all_day).page(params[:page]).reverse_order

  	  # 会員詳細からの遷移　＝＞　該当顧客の注文履歴
	  elsif path_controller == "admin/members" && path_action == "show"
	  @orders = Order.where(member_id: path[:id]).page(params[:page]).reverse_order

	  # ヘッダーからの遷移　＝＞　全顧客の注文履歴
	  else @orders = Order.all.page(params[:page]).reverse_order
	  end
  end

  def show
  	@order = Order.find(params[:id])
  	@order_details = @order.order_detail
  end

  def update
  	@order = Order.find(params[:id])
  	@order.update(order_params)
    @order_details = @order.order_detail
  	if @order.status == "入金確認"
  		@order_details.each do |order_detail|
  			order_detail.update(production_status: "製作待ち")
  		end
  	end
  	redirect_to request.referer
  end

  # def update_products
  # 	@product = OrderDetail.find(params[:id])
  # 	@product.update(order_detail_params)
  # end

  private

  def order_params
  	params.require(:order).permit(:status)
  end

  def order_detail_params
  	params.require(:order_detail).permit(:production_status)
  end

end

app/controllers/member/cart_products_controller.rb
class Member::CartProductsController < ApplicationController

private
	def cart_product_params
		params.require(:cart_product).permit(:cart_id, :product_id, :number)
	end
end

app/controllers/member/carts_controller.rb
class Member::CartsController < ApplicationController
	before_action :authenticate_member!

	def index
		@cart = current_member.cart || current_member.create_cart
		@cart_products = CartProduct.where(cart_id: current_member.cart.id)
	end

	def create
		@cart_product = CartProduct.new(cart_product_params)
		cart = current_member.cart || current_member.create_cart
		@cart_product.cart_id = current_member.cart.id
		@cart_products = CartProduct.where(cart_id: current_member.cart.id)
		@cart_products.each do |cart_product|
			if cart_product.product_id == @cart_product.product_id
				new_number = cart_product.number + @cart_product.number
				cart_product.update_attribute(:number, new_number)
				@cart_product.delete
			end
		end
		@cart_product.save
		redirect_to member_carts_path, notice: "カートに商品が追加されました"
	end

	def update
		@cart_product = CartProduct.find(params[:id])
		@cart_product.update(cart_product_params)
		redirect_to request.referer, notice: "変更されました"
	end

	def destroy
	 	@cart_product = CartProduct.find(params[:id])
	 	@cart_product.destroy
	 	redirect_to request.referer, notice: "カートから商品が削除されました"
	end

	def empty_item
		@cart_products = CartProduct.where(cart_id: current_member.cart.id)
		@cart_products.destroy_all
		redirect_to request.referer, notice: "カートを空にしました"
	end

	private
	def cart_product_params
		params.require(:cart_product).permit(:cart_id, :product_id, :number)
	end


end

app/controllers/member/orders_controller.rb
class Member::OrdersController < ApplicationController
  before_action :set_member
  def new
    @order = Order.new
    @shipping_addresses = ShippingAddress.where(member_id: current_member.id)
  end

  def create
    @order = Order.new(order_params)
    @order.member_id = current_member.id
    @order.payment_method = params[:order][:payment_method]
    @order.address_option = params[:order][:address_option]
    @order.postal_code = params[:order][:postal_code]
    @order.address = params[:order][:address]
    @order.address_name = params[:order][:address_name]
    @order.total_amount = params[:order][:total_amount]
    @order.save
    @cart_products = CartProduct.where(cart_id: current_member.cart.id)
    @cart_products.each do |cp|
      @order_detail = @order.order_detail.new
      @order_detail.product_id = cp.product.id
      @order_detail.number = cp.number
      @order_detail.taxed_price = cp.tax_price
      @order_detail.save
      cp.destroy
    end

    if ShippingAddress.find_by(member_id: current_member.id, address: @order.address).nil?
      @shipping_address = ShippingAddress.new
      @shipping_address.post_code = @order.postal_code
      @shipping_address.address = @order.address
      @shipping_address.address_name = @order.address_name
      @shipping_address.member_id = current_member.id
      @shipping_address.save
    end
    redirect_to member_orders_thank_path
  end

  def confirm
    @order = Order.new
    @cart = current_member.cart
    @cart_products = CartProduct.where(cart_id: current_member.cart.id)
    @order.member_id = current_member.id
    @order.payment_method = params[:order][:payment_method]
    @order.address_option = params[:order][:address_option]
    if @order.address_option == 0
      @order.postal_code = current_member.post_code
      @order.address = current_member.address
      @order.address_name = current_member.last_name + current_member.first_name
    elsif @order.address_option == 1
      @select_address = params[:order][:select_address]
      @shipping_address = ShippingAddress.find(@select_address)
      @order.postal_code = @shipping_address.post_code
      @order.address = @shipping_address.address
      @order.address_name = @shipping_address.address_name
    elsif @order.address_option == 2
      @order.postal_code = params[:order][:postal_code]
      @order.address = params[:order][:address]
      @order.address_name = params[:order][:address_name]
    end
    # render :new and return if params[:back] || !@order.save
  end



  def thank
    current_member.cart.cart_products.destroy_all
  end


  def index
		@orders = Order.where(member_id: current_member.id).page(params[:page]).per(8)
    @order_detail = OrderDetail.find_by(order_id: @order)
    #@orders = @member.orders
	end

	def show
    @order = Order.find_by(id: params[:id])
    @order_details = @order.order_detail
  end


  private
  def set_member
    @member = current_member
  end
  def order_params
    params.permit(
      :postage,
      :payment_method,
      :total_amount,
      :postal_code,
      :address,
      :address_name,
      :address_option,
      order_detail_attributes: [:id,
                                :product_id,
                                :product_name,
                                :order_id,
                                :number,
                                :taxed_price,
                                :production_status]
    ).merge(member_id: current_member.id)

  end

  def shipping_address_params
    params.require(:shipping_address).permit(:member_id, :post_code, :address, :address_name)
  end
end

app/controllers/member/products_controller.rb
class Member::ProductsController < ApplicationController
	def index
		@genres = Genre.where.not(disabled: "true")
		if params[:genre_id]
		@products = Product.where(genre_id: params[:genre_id]).page(params[:page]).reverse_order
		@genre = Genre.find_by(id: params[:genre_id])
	  else
		@products = Product.page(params[:page]).reverse_order
	    end
	end

	def show
		@genres = Genre.all
		@product = Product.find(params[:id])
		@cart_product = CartProduct.new
	end
end

app/controllers/member/shipping_addresses_controller.rb
class Member::ShippingAddressesController < ApplicationController
	before_action :authenticate_member!
	before_action :ensure_correct_member, only: [:edit, :update, :destroy]

	def index
		@shipping_addresses = ShippingAddress.where(member_id: current_member.id)
		@shipping_address = ShippingAddress.new

	end

	def create
		@shipping_address = ShippingAddress.new(shipping_address_params)
		@shipping_address.member_id = current_member.id
		if @shipping_address.save
	       redirect_to :action => 'index'
	    else
	       @shipping_addresses = ShippingAddress.where(member_id: current_member.id)
	   	   render 'index'
	    end
	end

	def edit
	end

	def update
		if @shipping_address.update(shipping_address_params)
			redirect_to :action => 'index'
		else
			render 'edit'
		end
	end

	def destroy
		@shipping_address.destroy
		redirect_to :action => 'index'
	end

	private

	def shipping_address_params
		params.require(:shipping_address).permit(:member_id, :post_code, :address, :address_name)
	end

	def ensure_correct_member
		@shipping_address = ShippingAddress.find(params[:id])
		unless @shipping_address.member == current_member
			redirect_to root_path
		end
	end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :authenticate_member!, only: [:show, :edit, :update, :withdraw, :hide]

	def edit
	  	@member = Member.find(params[:id])
	  	if current_member.id != @member.id
	  		redirect_to members_top_path(@member)
	  	end
	end

	def show
	  	@member = current_member
	end

	def update
	    @member = current_member
	    if @member.update(member_params)
	      redirect_to member_path(@member), success: 'お客様情報が更新されました！'
	    else
	      flash[:danger] = 'お客様の情報を更新出来ませんでした。空欄の箇所はありませんか？'
	      render :edit
	    end
	end

	def withdraw
	end

	def top
		@genres = Genre.where.not(disabled: "true")
		@products = Product.order("RANDOM()").limit(4)
	end

	def about
	end

    def hide
    	@member = current_member
	    @member.update(status: true)
	    reset_session
	    redirect_to members_top_path, info: 'ありがとうございました。またのご利用を心よりお待ちしております。'
    end

	  private

	  def member_params
	    params.require(:member).permit(:status, :first_name, :last_name, :first_name_kana, :last_name_kana, :post_code, :address, :email, :phone_number)
	  end
end

app/helpers/admin/members_helper.rb
module Admin::MembersHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/member/cart_prodicts_helper.rb
module Member::CartProdictsHelper
end

app/helpers/member/carts_helper.rb
module Member::CartsHelper
end

app/helpers/member/order_helper.rb
module Member::OrderHelper
end

app/helpers/member/orders_helper.rb
module Member::OrdersHelper
end

app/helpers/member/products_helper.rb
module Member::ProductsHelper
end

app/helpers/member/shipping_addresses_helper.rb
module Member::ShippingAddressesHelper
end

app/helpers/members_helper.rb
module MembersHelper
	def addTax(money,rate)
   taxed_money =  (money*rate).round
   "税込#{taxed_money}円"
  end
end

app/views/member/orders/confirm.html.erb
<div class="col-xs-9 col-xs-offset-3">
  <div>
    <h2>注文情報確認</h2>
  </div>
</div>
<div class="col-xs-7 col-xs-offset-1">

      <table class="table table-bordered">

        <thead>
          <tr>
            <th>商品名</th>
            <th>単価（税込）</th>
            <th>数量</th>
            <th>小計</th>
          </tr>
        </thead>

        <tbody>
          <%= form_with(model: [:member, @order], local: true,) do |f| %>

          <% @cart_products.each do |cart| %>
          <tr>
            <td><%= attachment_image_tag(cart.product, :image, :fill, 50, 50, fallback: "img/no-image.png", size: "50x50") %>
            <%= cart.product.name %></td>
            <td style="text-align: center; font-size: 20px;"> <%= cart.tax_price.floor %></td>
            <td><%= cart.number %></td>
            <td><%= cart.sum_price.floor %></td>
          </tr>

        </tbody>
        <%= f.hidden_field :member_id %>
        <% end %>

      </table>
</div>
<div class="col-xs-3">

        <table class="table table-bordered">
              <tr>
                <th>送料</th>
                <td><%= @order.postage %></td>
                <%= f.hidden_field :postage %><br>
              </tr>

              <tr>
                <th>商品合計</th>
                <td><%= @cart.total_price.floor %></td>
              </tr>

              <tr>
                <th>請求金額</th>
                <td><%= @order.payment_amount %> </td>

                <%= f.hidden_field :total_amount, value: @order.payment_amount %><br>
        </table>
</div>

<div class="col-xs-7 col-xs-offset-1">
    <div>
        <span style="font-size: x-large">
          <strong>支払方法</strong> :
          <%= @order.payment_method %>
          <%= f.hidden_field :payment_method %>
      </span>
    </div>
    <div>
        <span style="font-size: x-large">
          <strong>お届け先</strong> :
          <% @order.address_option %>
          <%= f.hidden_field :address_option, value: @order.address_option %>
          <%= @order.postal_code %>
          <%= f.hidden_field :postal_code, value: @order.postal_code %>  
          <%= @order.address %>
          <%= f.hidden_field :address, value: @order.address %>  
          <%= @order.address_name %>  様
          <%= f.hidden_field :address_name, value: @order.address_name %>
      </span>
    </div>
</div>
<div class="col-xs-3 col-xs-offset-4">
     <%= f.submit "購入を確定する", class: "btn btn-success center-block btn-lg" %>
</div>
      <% end %>
</div>




</div>

app/views/member/orders/index.html.erb
<div class="container">
<h2>注文履歴一覧</h2>
<table class="table">
	<thead class="thead-light">
		<tr>
			<th>注文日</th>
			<th>配送先</th>
			<th>注文商品</th>
			<th>支払金額</th>
			<th>ステータス</th>
			<th>注文詳細</th>
		</tr>
	</thead>
	<% @orders.each do |order| %>
	<tr>
		<td><%= order.created_at.strftime('%Y/%m/%d ') %></td>
		<td><%= order.postal_code %><br>
				<%= order.address %><br>
				<%= order.address_name %></td>
		<td><% order.order_detail.each do |order_detail| %>
					<%= order_detail.product.name %></br>
					<% end %></td>
		<td><%= order.total_amount %></td>
		<td><%= order.status %></td>
		<td><%= link_to "表示する" , member_order_path(order),class:'btn btn-default' %>
		</td>
	</tr>
	<% end %>
</table>
<%= paginate @orders %>
</div>

app/views/member/orders/new.html.erb
<div class="col-xs-9 col-xs-offset-1">
<h2>注文情報入力</h1>

<%= form_with(model: [ :member, @order], local: true, url: { action: :confirm }) do |f| %>

<h3>支払方法</h3>
<div class="field">
    <div class="form-group">
        <label><%= f.radio_button :payment_method, :クレジットカード, checked: "checked" %> クレジットカード</label>
    </div>
    <div class="form-group">
        <label><%= f.radio_button :payment_method, :銀行振込 %> 銀行振込</label>
    </div>
</div>

<h3>お届け先</h3>
<div class="field">
    <div class="form-group">
        <label><%= f.radio_button :address_option, 0, checked: "checked" %> ご自身の住所</label><br />
        <%= current_member.full_address %><br>
        <%= current_member.last_name %>
    </div>
    <div class="form-group">
        <label><%= f.radio_button :address_option, 1 %> 登録済住所から選択</label><br />
        <%= f.collection_select :select_address, @shipping_addresses, :id, :full_address %>
    </div>

    <div class="form-group">
        <label><%= f.radio_button :address_option, 2 %> 新しいお届け先</label><br />

        <%= f.label :郵便番号 %>
        <%= f.text_field :postal_code %><br>
        <%= f.label :住所 %>
        <%= f.text_field :address %><br>
        <%= f.label :宛名 %>
        <%= f.text_field :address_name %><br>
    </div>
</div>

<%= f.submit "確認画面へ進む", class: "btn btn-success center-block btn-lg" %>

<% end %>
</div>

app/views/member/orders/show.html.erb
<div class="container">
<h2>注文履歴詳細</h2>
<div class="row">
<div class="col-xs-6 col-xs-offset-1">
	<table class="table">
		<caption align="left">1注文情報</caption>
		<tr>
			<td>注文日</td>
			<td><%= @order.created_at.strftime('%Y/%m/%d ') %></td>
		</tr>
		<tr>
			<td>配送先</td>
			<td><%= @order.member.post_code %><br>
                <%= @order.member.address %><br>
                <%= @order.member.last_name %>
                <%= @order.member.first_name %>
			 </td>
		</tr>
		<tr>
			<td>支払方法</td>
			<td><%= @order.payment_method %></td>
		</tr>
		<tr>
			<td>ステータス</td>
			<td><%= @order.status %></td>
		</tr>
	</table>
</div>
<div class="col-xs-3">
	<table class="table">
		<caption align="left">2請求情報</caption>
		<tr>
			<td>商品合計</td>
			<td><%= @order.total_amount - @order.postage%></td>
		</tr>
		<tr>
			<td>配送料</td>
			<td><%= @order.postage %></td>
		</tr>
		<tr>
			<td>ご請求額</td>
			<td><%=  @order.total_amount %></td>
		</tr>
	</table>
</div>
	<div class="col-xs-10 col-xs-offset-1">
	<table class="table">
		<caption align="left">注文内容</caption>
		<thead>
		<tr>
			<th>商品</th>
			<th>単価（税込み）</th>
			<th>個数</th>
			<th>小計</th>
		</tr>
	</thead>
	<% @sum = 0 %>
	<% @order_details.each do |order_detail| %>
		<tr>
			<td><%= order_detail.product.name %></td>
			<td><%= order_detail.taxed_price %></td>
			<td><%= order_detail.number %> </td>
			<td><%= order_detail.taxed_price * order_detail.number %>
				<% @sum += order_detail.taxed_price * order_detail.number %>
			</td>
		</tr>
		<% end %>
	</table>
</div>
</div>
</div>

app/views/member/orders/thank.html.erb
<div class="thank">
  <h1 class="thank-text">ご購入ありがとうございました！</h1>
</div>