config/routes.rb
Rails.application.routes.draw do
  devise_for :members

  get "/members/about" => "members#about"
  get "/members/top" => "members#top"
  get "/members/withdraw" => "members#withdraw"
  patch "/members/hide" => "members#hide"
  resources :members

  devise_scope :admin do
    root "admins/sessions#new"
  end

  devise_for :admins, controllers: {
    sessions: 'admins/sessions'
  }

  get 'admin/top' => "admin/homes#top"

  namespace :admin do
    resources :orders, only: [:index, :show, :update]
    # patch '/orders/:id/update' => 'orders#update'
    resources :order_details, only: [:update]
    resources :members, only: [:show, :edit, :update, :index]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :products, xcept: [:destroy]
    get '/search' => 'search#search'
  end

  namespace :member do
      resources :products, only: [:index, :show]
      resources :carts, only: [:index, :create, :update, :destroy]
      delete '/empty_item' => 'carts#empty_item'
      resources :cart_products
      resources :shipping_addresses, only: [:index, :create, :edit, :update, :destroy]
      post 'order/confirm' => "orders#confirm"
      get 'orders/thank' => "orders#thank"
      resources :orders, only: [:index, :show, :new, :create]
  end


end

app/models/product.rb
class Product < ApplicationRecord
	attachment :image

	has_many :cart_products, dependent: :destroy
	belongs_to :genre, foreign_key: "genre_id"

	validates :name, presence: true
	validates :description, presence: true
	validates :genre_id, presence: true
	validates :price, presence: true
	validates :salling_status, presence: true

	enum salling_status: { 販売中: 0, 売切: 1}

	def tax_price
  	  price * 1.1
    end


end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @products = Product.page(params[:page]).per(8)
    @genres = Genre.all
  end

  def new
    @product_new = Product.new
    @genres = Genre.where.not(disabled: "true")
  end

  def create
    @product_new = Product.new(product_params)
    if @product_new.save
       redirect_to admin_product_path(@product_new), notice: "登録されました"
     else
      @genres = Genre.where.not(disabled: "true")
      render 'new', notice: "空欄はありませんか？"
    end
  end

  def show
    @product = Product.find(params[:id])
  end

  def edit
    @product = Product.find(params[:id])
    @genres = Genre.where.not(disabled: "true")
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
       redirect_to admin_product_path(@product), notice: "更新されました"
     else
      @genres = Genre.where.not(disabled: "true")
      render 'edit', notice: "空欄はありませんか？"
    end
  end



  private

  def product_params
    params.require(:product).permit(:image, :name, :description, :genre_id, :price, :salling_status)
  end

end

app/controllers/member/products_controller.rb
class Member::ProductsController < ApplicationController
	def index
		@genres = Genre.where.not(disabled: "true")
		if params[:genre_id]
		@products = Product.where(genre_id: params[:genre_id]).page(params[:page]).reverse_order
		@genre = Genre.find_by(id: params[:genre_id])
	  else
		@products = Product.page(params[:page]).reverse_order
	    end
	end

	def show
		@genres = Genre.all
		@product = Product.find(params[:id])
		@cart_product = CartProduct.new
	end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/member/products_helper.rb
module Member::ProductsHelper
end

app/views/products/show.html 2.erb
<!doctype html>
<html lang="ja">
	<head>
	    <!-- Required meta tags -->
	    <meta charset="utf-8">
	    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	    <!-- Bootstrap CSS -->
	    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

	    <title>商品詳細</title>
	</head>
 	<body>
 		<div class="container">
 			<div class="row"><h1>商品詳細</h1></div>
 			<div class="row">
				<div class="col-lg-4">
					<%= attachment_image_tag @product, :image, :fill, 300, 300 %>
				</div>
				<div class="col-lg-8">
					<dl>
						<dt>商品名</dt>
						<dd><%= @product.name %></dd>
						<dt>商品説明</dt>
						<dd><%= @product.description %></dd>
						<dt>ジャンル</dt>
						<dd><%= @product.genre.name %></dd>
						<dt>税込価格（税抜価格）</dt>
						<dd><%= @product.price %>(order_detailsから販売価格持ってくる？）円</dd>
						<dt>販売ステータス</dt>
						<dd><%= @product.salling_status_i18n %></dd>
					</dl>

					<%= link_to '編集する', edit_product_path, class: "btn btn-info" %>
				</div>
			</div>
		</div>
	</body>